"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("reflect-metadata");
const appolo_engine_1 = require("appolo-engine");
const appolo_utils_1 = require("appolo-utils");
const defaults_1 = require("./src/defaults/defaults");
const validator_1 = require("./src/validator/validator");
exports.Validator = validator_1.Validator;
const anySchema_1 = require("./src/types/any/anySchema");
exports.any = anySchema_1.any;
exports.AnySchema = anySchema_1.AnySchema;
const numberSchema_1 = require("./src/types/number/numberSchema");
exports.number = numberSchema_1.number;
const stringSchema_1 = require("./src/types/string/stringSchema");
exports.string = stringSchema_1.string;
const arraySchema_1 = require("./src/types/array/arraySchema");
exports.array = arraySchema_1.array;
const objectSchema_1 = require("./src/types/object/objectSchema");
exports.object = objectSchema_1.object;
const functionSchema_1 = require("./src/types/function/functionSchema");
exports.func = functionSchema_1.func;
const ref_1 = require("./src/schema/ref");
exports.ref = ref_1.ref;
const when_1 = require("./src/when/when");
exports.when = when_1.when;
const bufferSchema_1 = require("./src/types/buffer/bufferSchema");
exports.buffer = bufferSchema_1.buffer;
const booleanSchema_1 = require("./src/types/boolean/booleanSchema");
exports.boolean = booleanSchema_1.boolean;
const orConstraint_1 = require("./src/types/any/constraints/orConstraint");
exports.or = orConstraint_1.or;
const andConstraint_1 = require("./src/types/any/constraints/andConstraint");
exports.and = andConstraint_1.and;
const dateSchema_1 = require("./src/types/date/dateSchema");
exports.date = dateSchema_1.date;
const registerConstraint_1 = require("./src/schema/registerConstraint");
exports.registerConstraint = registerConstraint_1.registerConstraint;
const registerConverter_1 = require("./src/schema/registerConverter");
exports.registerConverter = registerConverter_1.registerConverter;
const decorators_1 = require("./src/decorators/decorators");
exports.schema = decorators_1.schema;
const numberSchema_2 = require("./src/types/number/numberSchema");
exports.NumberSchema = numberSchema_2.NumberSchema;
const stringSchema_2 = require("./src/types/string/stringSchema");
exports.StringSchema = stringSchema_2.StringSchema;
const arraySchema_2 = require("./src/types/array/arraySchema");
exports.ArraySchema = arraySchema_2.ArraySchema;
const objectSchema_2 = require("./src/types/object/objectSchema");
exports.ObjectSchema = objectSchema_2.ObjectSchema;
const booleanSchema_2 = require("./src/types/boolean/booleanSchema");
exports.BooleanSchema = booleanSchema_2.BooleanSchema;
const dateSchema_2 = require("./src/types/date/dateSchema");
exports.DateSchema = dateSchema_2.DateSchema;
const bufferSchema_2 = require("./src/types/buffer/bufferSchema");
exports.BufferSchema = bufferSchema_2.BufferSchema;
const functionSchema_2 = require("./src/types/function/functionSchema");
exports.FunctionSchema = functionSchema_2.FunctionSchema;
const ValidationError_1 = require("./src/common/errors/ValidationError");
exports.ValidationError = ValidationError_1.ValidationError;
const ValidationErrorsError_1 = require("./src/common/errors/ValidationErrorsError");
exports.ValidationErrorsError = ValidationErrorsError_1.ValidationErrorsError;
require("./src/types/any/constraints/requiredConstraint");
require("./src/types/number/converters/numberConverter");
require("./src/types/number/converters/precisionConverter");
require("./src/types/number/converters/integerConverter");
require("./src/types/number/constraints/integerNumberConstraint");
require("./src/types/number/constraints/maxNumberConstraint");
require("./src/types/number/constraints/minNumberConstraint");
require("./src/types/number/constraints/multipleNumberConstraint");
require("./src/types/number/constraints/negativeNumberConstraint");
require("./src/types/number/constraints/numberConstraint");
require("./src/types/number/constraints/portNumberConstraint");
require("./src/types/number/constraints/positiveNumberConstraint");
require("./src/types/object/constraints/keysConstraint");
require("./src/types/object/constraints/instanceOfConstraint");
require("./src/types/object/constraints/isObjectConstraint");
require("./src/types/object/constraints/isObjectOrClassConstraint");
require("./src/types/object/constraints/isPlainConstraint");
require("./src/types/object/constraints/maxKeysConstraint");
require("./src/types/object/constraints/minKeysConstraint");
require("./src/types/object/constraints/sizeConstraint");
require("./src/types/object/constraints/withConstraint");
require("./src/types/object/constraints/withoutConstraint");
require("./src/types/object/converters/jsonConverter");
require("./src/types/function/constraints/maxArgsConstraint");
require("./src/types/function/constraints/argsSizeConstraint");
require("./src/types/function/constraints/funcConstraint");
require("./src/types/function/constraints/isClassConstraint");
require("./src/types/function/constraints/minArgsConstraint");
require("./src/types/date/constraints/isDateConstraint");
require("./src/types/date/constraints/maxConstraint");
require("./src/types/date/constraints/minConstraint");
require("./src/types/date/converters/dateConverter");
require("./src/types/buffer/converters/toBufferConverter");
require("./src/types/buffer/constraints/minConstraint");
require("./src/types/buffer/constraints/maxConstraint");
require("./src/types/buffer/constraints/sizeConstraint");
require("./src/types/buffer/constraints/bufferConstraint");
require("./src/types/boolean/constraints/booleanConstraint");
require("./src/types/boolean/converters/toBooleanConverter");
require("./src/types/array/converters/toSortConverter");
require("./src/types/array/converters/toUniqConverter");
require("./src/types/array/constraints/arrayConstraint");
require("./src/types/array/constraints/containsConstraint");
require("./src/types/array/constraints/hasConstraint");
require("./src/types/array/constraints/itemsConstraint");
require("./src/types/array/constraints/maxConstraint");
require("./src/types/array/constraints/minConstraint");
require("./src/types/array/constraints/sizeConstraint");
require("./src/types/array/constraints/uniqConstraint");
require("./src/types/any/constraints/requiredConstraint");
require("./src/types/any/constraints/andConstraint");
require("./src/types/any/constraints/forbiddenConstraint");
require("./src/types/any/constraints/invalidConstraint");
require("./src/types/any/constraints/optionalConstraint");
require("./src/types/any/constraints/orConstraint");
require("./src/types/any/constraints/validConstraint");
require("./src/types/any/constraints/allowConstraint");
require("./src/types/any/converters/defaultConverter");
require("./src/types/any/converters/promiseConverter");
require("./src/when/whenConstraint");
require("./src/types/string/constraints/alphanumStringConstraint");
require("./src/types/string/constraints/alphaStringConstraint");
require("./src/types/string/constraints/asciiStringConstraint");
require("./src/types/string/constraints/base64StringConstraint");
require("./src/types/string/constraints/domainStringConstraint");
require("./src/types/string/constraints/emailStringConstraint");
require("./src/types/string/constraints/enumStringConstraint");
require("./src/types/string/constraints/hashStringConstraint");
require("./src/types/string/constraints/hexadecimalStringConstraint");
require("./src/types/string/constraints/ipStringConstraint");
require("./src/types/string/constraints/isoDateStringConstraint");
require("./src/types/string/constraints/jsonStringConstraint");
require("./src/types/string/constraints/jwtStringConstraint");
require("./src/types/string/constraints/lowerCaseStringConstraint");
require("./src/types/string/constraints/maxStringConstraint");
require("./src/types/string/constraints/md5StringConstraint");
require("./src/types/string/constraints/minStringConstraint");
require("./src/types/string/constraints/mongoIdStringConstraint");
require("./src/types/string/constraints/numericStringConstraint");
require("./src/types/string/constraints/regexStringConstraint");
require("./src/types/string/constraints/sizeStringConstraint");
require("./src/types/string/constraints/slugStringConstraint");
require("./src/types/string/constraints/stringConstraint");
require("./src/types/string/constraints/tokenStringConstraint");
require("./src/types/string/constraints/upperCaseStringConstraint");
require("./src/types/string/constraints/urlStringConstraint");
require("./src/types/string/constraints/uuidStringConstraint");
require("./src/types/string/converters/decodeConverter");
require("./src/types/string/converters/replaceConverter");
require("./src/types/string/converters/sanitizeConverter");
require("./src/types/string/converters/slugifyConverter");
require("./src/types/string/converters/trimConverter");
require("./src/types/string/converters/truncateConverter");
const registerSchema_1 = require("./src/schema/registerSchema");
exports.registerSchema = registerSchema_1.registerSchema;
const when_2 = require("./src/when/when");
exports.When = when_2.When;
async function validation(options = {}) {
    let app = appolo_engine_1.createApp({ root: __dirname });
    app.injector.addObject("options", appolo_utils_1.Objects.defaults({}, options, defaults_1.ValidatorDefaults));
    await app.launch();
    let server = app.injector.get(validator_1.Validator);
    return server;
}
exports.validation = validation;
//# sourceMappingURL=index.js.map